In [35]:
import numpy as np
import pandas as pd

## Create a df

In [36]:
# Way1
arr1 = np.array(
    [
     [1,2],
     [3,4]
    ]
)
df1 = pd.DataFrame(arr1)
df1

0  1
0  1  2
1  3  4

In [37]:
# Way2
arr2 = {
    "col1" : [1,2],
    "col2" : [3,4]
}

df2 = pd.DataFrame(arr2, columns=["col1", "col2"])

df2

col1  col2
0     1     3
1     2     4

In [38]:
# shape
df2.shape

(2, 2)

In [39]:
# statistics
df2.describe()

col1      col2
count  2.000000  2.000000
mean   1.500000  3.500000
std    0.707107  0.707107
min    1.000000  3.000000
25%    1.250000  3.250000
50%    1.500000  3.500000
75%    1.750000  3.750000
max    2.000000  4.000000

## operations on vector

In [40]:
# most oper are not inplace (and should not be!)
np.max(arr1)

4

In [41]:
arr1.reshape(4,1)

array([[1],
       [2],
       [3],
       [4]])

In [42]:
arr1.T

array([[1, 3],
       [2, 4]])

In [43]:
arr1.flatten()

array([1, 2, 3, 4])

In [44]:
arr1.flatten() == arr1.reshape(1,-1)

array([[ True,  True,  True,  True]])

In [45]:
np.sum(arr1.diagonal()) == arr1.trace()

True

In [46]:
arr1 + arr1

array([[2, 4],
       [6, 8]])

In [47]:
# individual mul
arr1 * arr1

array([[ 1,  4],
       [ 9, 16]])

In [48]:
# matrix mul
np.dot(arr1, arr1)

array([[ 7, 10],
       [15, 22]])

## linalg

In [49]:
np.linalg.det(arr1)

-2.0000000000000004

In [50]:
np.linalg.eig(arr1)

(array([-0.37228132,  5.37228132]), array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

In [51]:
np.linalg.inv(arr1)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

$ BY Gaurav Kabra $